server:
    # build: .
    image: intropro/single-node-cloudera-env
    hostname: cm1.bigdata
    privileged: true
    # net: "host"
    ports:
        - "8022:22"     # ssh
        - "7180:7180"   # Cloudera Manager
        - "8888:8888"   # HUE
        - "11000:11000" # Oozie
        - "50070:50070" # HDFS REST Namenode